# Generated by Django 5.2.9 on 2025-12-09 01:31

import api_noticias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200, validators=[api_noticias.models.validar_titulo_largo]),
        ),
    ]
